name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - run: ./mvnw package
  AWS-Deploy:
    # disable job
    if: 1 == 0
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SSH_KEY }} | base64 -d > key.pem
      - run: chmod 400 key.pem
      - run: ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@csa-backend.rohanj.dev 'cd ~/tri2/t8_csaspring; git pull; docker-compose down; docker-compose up -d --build'
